### PR TITLE
Make plugin to work with most recent version of mjml

### PR DESCRIPTION
**Pull request by graycrow**
Fix for #6

### CODE REVIEW

**Comment by jeffreyschmitz87** [comment]
A colleague has to look in to your pull request but he's on vacation right now. When he's back he'll look into your pull request 👍

**Comment by aureliusm** [comment]
@jeffreyschmitz87 Any info on the timeline on this. It is quite important for us. Thanks :)

**Comment by johnvanhulsen** [comment]
@aureliusm accept PR's in v1.4.0 👍
https://github.com/tdeNL/tde-webpack-mjml-plugin/releases/tag/v1.4.0

**Comment by aureliusm** [comment]
@johnvanhulsen Awesome, thanks for your quick response!

**Comment by aureliusm** [comment]
@johnvanhulsen NPM still shows 1.3.0 as the last version? https://www.npmjs.com/package/tde-webpack-mjml-plugin

**Comment by jordikroon** [comment]
@aureliusm Thanks for spotting. I've just published to NPM!

**Pull request merged**
